=== CesarTaco1007/app-web-CPTA/01-HTML5-CSS3/05-XML/contactos.dtd
<!DOCTYPE Contactos [
        <!ELEMENT Contactos (contacto)*>
        <!ELEMENT contacto (informacion-personal|empresa|telefono|localizacion|tonos)*>
        <!ATTLIST contacto id CDATA #REQUIRED>
        <!ELEMENT informacion-personal (fotografia|titulo|nombre|apellido|url-pagina-personal|fecha-cumpleaños)*>
        <!ELEMENT fotografia (#PCDATA)>
        <!ELEMENT titulo (#PCDATA)>
        <!ELEMENT nombre (#PCDATA)>
        <!ELEMENT apellido (#PCDATA)>
        <!ELEMENT url-pagina-personal (#PCDATA)>
        <!ELEMENT fecha-cumpleaños (#PCDATA)>
        <!ELEMENT empresa (nombreEmpresa|tipoEmpresa)*>
        <!ELEMENT nombreEmpresa (#PCDATA)>
        <!ELEMENT tipoEmpresa (#PCDATA)>
        <!ELEMENT telefono (celular|casa|trabajo|principal|fax)*>
        <!ELEMENT celular (#PCDATA)>
        <!ELEMENT casa (#PCDATA)>
        <!ELEMENT trabajo (#PCDATA)>
        <!ELEMENT principal (#PCDATA)>
        <!ELEMENT fax (#PCDATA)>
        <!ELEMENT localizacion (pais|ciudad|geolocalizacion)*>
        <!ELEMENT pais (#PCDATA)>
        <!ELEMENT ciudad (#PCDATA)>
        <!ELEMENT geolocalizacion (#PCDATA)>
        <!ELEMENT tonos (mensaje|llamada)*>
        <!ELEMENT mensaje (#PCDATA)>
        <!ELEMENT llamada (#PCDATA)>
        ]>

=== CesarTaco1007/app-web-CPTA/01-HTML5-CSS3/05-XML/contactos.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Contactos SYSTEM "contactos.dtd">
<Contactos>
	<contacto id="1">
        <informacion-personal>
            <fotografia>foto1</fotografia>
            <titulo>titulo1</titulo>
            <nombre>Nombre1</nombre>
            <apellido>Apellido1</apellido>
            <url-pagina-personal>URL1</url-pagina-personal>
            <fecha-cumpleaños>Fecha1</fecha-cumpleaños>
        </informacion-personal>
    <empresa>
        <nombreEmpresa>Empresa1</nombreEmpresa>
        <tipoEmpresa>Privada</tipoEmpresa>
    </empresa>
    <telefono>
        <celular>0995021739</celular>
        <casa>2810596</casa>
        <trabajo>022500105</trabajo>
        <principal>0995021739</principal>
        <fax>555666777888</fax>
    </telefono>
    <localizacion>
        <pais>Ecuador</pais>
        <ciudad>Quito</ciudad>
        <geolocalizacion>223.255.129.10</geolocalizacion>
    </localizacion>
    <tonos>
        <mensaje>message</mensaje>
        <llamada>alert</llamada>
    </tonos>
    </contacto>
    <contacto id="2">
        <informacion-personal>
            <fotografia>foto2</fotografia>
            <titulo>titulo2</titulo>
            <nombre>Nombre2</nombre>
            <apellido>Apellido2</apellido>
            <url-pagina-personal>URL2</url-pagina-personal>
            <fecha-cumpleaños>Fecha2</fecha-cumpleaños>
        </informacion-personal>
        <empresa>
            <nombreEmpresa>Empresa2</nombreEmpresa>
            <tipoEmpresa>Publica</tipoEmpresa>
        </empresa>
        <telefono>
            <celular>0991231739</celular>
            <casa>2812596</casa>
            <trabajo>022650105</trabajo>
            <principal>0991561739</principal>
            <fax>555666444888</fax>
        </telefono>
        <localizacion>
            <pais>Ecuador</pais>
            <ciudad>Quito</ciudad>
            <geolocalizacion>223.255.129.11</geolocalizacion>
        </localizacion>
        <tonos>
            <mensaje>message</mensaje>
            <llamada>alert</llamada>
        </tonos>
    </contacto>
    <contacto id="3">
        <informacion-personal>
            <fotografia>foto3</fotografia>
            <titulo>titulo3</titulo>
            <nombre>Nombre3</nombre>
            <apellido>Apellido3</apellido>
            <url-pagina-personal>URL3</url-pagina-personal>
            <fecha-cumpleaños>Fecha3</fecha-cumpleaños>
        </informacion-personal>
        <empresa>
            <nombreEmpresa>Empresa3</nombreEmpresa>
            <tipoEmpresa>Privada</tipoEmpresa>
        </empresa>
        <telefono>
            <celular>0991231456</celular>
            <casa>2812789</casa>
            <trabajo>022450105</trabajo>
            <principal>0991561739</principal>
            <fax>555666444999</fax>
        </telefono>
        <localizacion>
            <pais>Ecuador</pais>
            <ciudad>Quito</ciudad>
            <geolocalizacion>223.255.129.12</geolocalizacion>
        </localizacion>
        <tonos>
            <mensaje>message</mensaje>
            <llamada>alert</llamada>
        </tonos>
    </contacto>
</Contactos>
